# Remove color codes in log output
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG=y

# Increase stack memory to avoid crashes
CONFIG_MAIN_STACK_SIZE=8192

# Enable WiFi
CONFIG_WIFI=y

# Networking config
CONFIG_NETWORKING=y
CONFIG_NET_MGMT=y
CONFIG_NET_IPV4=y  # will rely on this in this example
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y  # For http requests
CONFIG_NET_SOCKETS=y

# CONFIG_NET_PKT_RX_COUNT=40
# CONFIG_NET_PKT_TX_COUNT=40
# CONFIG_NET_BUF_RX_COUNT=40
# CONFIG_NET_BUF_TX_COUNT=40

# Get IPv4 address from DHCP
CONFIG_NET_DHCPV4=y

# Enable DNS resolver
CONFIG_DNS_RESOLVER=y

# How long to wait for e.g., DHCP to provide an IP address (seconds)
CONFIG_NET_CONFIG_INIT_TIMEOUT=30

# Network debug config
CONFIG_NET_LOG=y

# Enable Ethernet (required for WiFi on ESP32 (do we need it for another chip?))#
# CONFIG_NET_L2_ETHERNET=y

# logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_MAX_LEVEL=4

# GPIO
CONFIG_GPIO=y

# Flash
CONFIG_FLASH=y

# # SPI
# CONFIG_SPI=y
# CONFIG_SPI_ASYNC=y
# CONFIG_SPI_SLAVE=y
# CONFIG_DMA=y
# CONFIG_SPI_MCUX_FLEXCOMM=y
# CONFIG_SPI_MCUX_FLEXCOMM_DMA=y

# Enable wifi utilities
CONFIG_WIFI_UTILITIES=y

# Enable TCP socket demo
CONFIG_TCP_SOCKET=y
CONFIG_TCP_SOCKET_THREAD_STACK_SIZE=32000

